name: Deploy to S3 with Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy site
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: terraform init \
          -backend-config="bucket=${{ secrets.BACKEND_BUCKET }}" \
          -backend-config="key=${{ secrets.BACKEND_KEY }}" \
          -backend-config="region=${{ secrets.AWS_REGION }}"
      

      - name: Terraform Apply
        run: terraform apply -auto-approve
